# pre-commit is a tool to perform a predefined set of tasks manually and/or
# automatically before git commits are made.
#
# Config reference: https://pre-commit.com/#pre-commit-configyaml---top-level
#
# Common tasks
#
# - Run on all files:   pre-commit run --all-files
# - Register git hooks: pre-commit install --hook-type pre-commit
#
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        description: Run ESLint (with autofix) across all packages
        entry: npx lerna run lint --stream -- --fix
        language: system
        pass_filenames: false
        types_or: [ts, tsx, javascript, jsx]
