/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  title: "xrpl.js Documentation",
  tagline:
    "This is the recommended library for integrating a JavaScript/TypeScript app with the XRP Ledger, especially if you intend to use advanced functionality such as IOUs, payment paths, the decentralized exchange, account settings, payment channels, escrows, multi-signing, and more.",
  url: "https://your-docusaurus-test-site.com",
  baseUrl: "/",
  organizationName: "facebook",
  projectName: "docusaurus",
  onBrokenLinks: "ignore",
  onBrokenMarkdownLinks: "warn",
  i18n: {
    defaultLocale: "en",
    locales: ["en"],
    path: "i18n",
    localeConfigs: {},
  },
  plugins: [
    [
      "docusaurus-plugin-typedoc-api",
      {
        id: "default",
        projectRoot: "/Users/jlei/Downloads/ripple/xrpl.js/",
        packages: [
          "packages/xrpl",
          "packages/ripple-keypairs",
          "packages/ripple-address-codec",
          "packages/ripple-binary-codec",
        ],
        debug: true,
        minimal: false,
        readmes: true,
        changelogs: true,
        changelogName: "HISTORY.md",
        typedocOptions: {
          categoryOrder: [
            "Constructor",
            "Clients",
            "Signing",
            "Transaction Models",
            "Transaction Flags",
            "Ledger Flags",
            "Utilities",
            "Requests",
            "Responses",
            "Streams",
            "Errors",
          ],
          categorizeByGroup: false,
          readme: "../../README.md",
        },
      },
    ],
    null,
    "docusaurus-plugin-sass",
  ],
  presets: [
    [
      "classic",
      {
        docs: {
          sidebarPath:
            "/Users/jlei/Downloads/ripple/xrpl.js/website/sidebars.js",
          editUrl:
            "https://github.com/facebook/docusaurus/tree/main/packages/create-docusaurus/templates/shared/",
        },
        theme: {
          customCss:
            "/Users/jlei/Downloads/ripple/xrpl.js/website/src/css/custom.scss",
        },
      },
    ],
  ],
  themeConfig: {
    image: "img/docusaurus-social-card.jpg",
    navbar: {
      title: "XRPL.JS",
      items: [
        {
          type: "docSidebar",
          sidebarId: "tutorialSidebar",
          position: "left",
          label: "Setup",
        },
        {
          href: "https://github.com/XRPLF/xrpl.js",
          label: "GitHub",
          position: "right",
        },
        {
          to: "api",
          label: "API",
          position: "left",
        },
      ],
      hideOnScroll: false,
    },
    footer: {
      style: "dark",
      links: [
        {
          title: "Docs",
          items: [
            {
              label: "xrpl.org",
              to: "https://xrpl.org ",
            },
            {
              label: "Quickstart",
              to: "/docs/intro",
            },
            {
              label: "xrpl.js",
              to: "/api/xrpl",
            },
            {
              label: "ripple-address-codec",
              to: "/api/ripple-address-codec",
            },
            {
              label: "ripple-keypairs",
              to: "/api/ripple-keypairs",
            },
          ],
        },
        {
          title: "Community",
          items: [
            {
              label: "Discord",
              href: "htpps://bit.ly/3TPCWon",
            },
            {
              label: "Twitter",
              href: "https://twitter.com/RippleXDev",
            },
          ],
        },
        {
          title: "More",
          items: [
            {
              label: "npm",
              to: "https://www.npmjs.com/package/xrpl",
            },
            {
              label: "GitHub",
              href: "https://github.com/XRPLF/xrpl.js",
            },
            {
              label: "XRPL Code Samples",
              href: "https://github.com/XRPLF/xrpl-dev-portal/tree/master/content/_code-samples",
            },
            {
              label: "Subscribe to xrpl-announce",
              href: "https://groups.google.com/g/xrpl-announce",
            },
            {
              label: "Subscribe to ripple-server",
              href: "https://groups.google.com/g/xrpl-announce",
            },
          ],
        },
      ],
      copyright: "Copyright © 2024 XRP Ledger. Open Source",
    },
    prism: {
      theme: {
        plain: {
          color: "#393A34",
          backgroundColor: "#f6f8fa",
        },
        styles: [
          {
            types: ["comment", "prolog", "doctype", "cdata"],
            style: {
              color: "#999988",
              fontStyle: "italic",
            },
          },
          {
            types: ["namespace"],
            style: {
              opacity: 0.7,
            },
          },
          {
            types: ["string", "attr-value"],
            style: {
              color: "#e3116c",
            },
          },
          {
            types: ["punctuation", "operator"],
            style: {
              color: "#393A34",
            },
          },
          {
            types: [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted",
            ],
            style: {
              color: "#36acaa",
            },
          },
          {
            types: ["atrule", "keyword", "attr-name", "selector"],
            style: {
              color: "#00a4db",
            },
          },
          {
            types: ["function", "deleted", "tag"],
            style: {
              color: "#d73a49",
            },
          },
          {
            types: ["function-variable"],
            style: {
              color: "#6f42c1",
            },
          },
          {
            types: ["tag", "selector", "keyword"],
            style: {
              color: "#00009f",
            },
          },
        ],
      },
      darkTheme: {
        plain: {
          color: "#F8F8F2",
          backgroundColor: "#282A36",
        },
        styles: [
          {
            types: ["prolog", "constant", "builtin"],
            style: {
              color: "rgb(189, 147, 249)",
            },
          },
          {
            types: ["inserted", "function"],
            style: {
              color: "rgb(80, 250, 123)",
            },
          },
          {
            types: ["deleted"],
            style: {
              color: "rgb(255, 85, 85)",
            },
          },
          {
            types: ["changed"],
            style: {
              color: "rgb(255, 184, 108)",
            },
          },
          {
            types: ["punctuation", "symbol"],
            style: {
              color: "rgb(248, 248, 242)",
            },
          },
          {
            types: ["string", "char", "tag", "selector"],
            style: {
              color: "rgb(255, 121, 198)",
            },
          },
          {
            types: ["keyword", "variable"],
            style: {
              color: "rgb(189, 147, 249)",
              fontStyle: "italic",
            },
          },
          {
            types: ["comment"],
            style: {
              color: "rgb(98, 114, 164)",
            },
          },
          {
            types: ["attr-name"],
            style: {
              color: "rgb(241, 250, 140)",
            },
          },
        ],
      },
      additionalLanguages: [],
      magicComments: [
        {
          className: "theme-code-block-highlighted-line",
          line: "highlight-next-line",
          block: {
            start: "highlight-start",
            end: "highlight-end",
          },
        },
      ],
    },
    colorMode: {
      defaultMode: "dark",
      disableSwitch: false,
      respectPrefersColorScheme: false,
    },
    algolia: {
      appId: "UWLAFN5MGH",
      apiKey: "f7b1b6b53eda9a560bf206a5148207d8",
      indexName: "js-xrpl",
      contextualSearch: true,
      externalUrlRegex: "external\\.com|domain\\.com",
      replaceSearchResultPathname: {
        from: "/docs/",
        to: "/",
      },
      searchParameters: {},
      searchPagePath: "search",
    },
    docs: {
      versionPersistence: "localStorage",
      sidebar: {
        hideable: false,
        autoCollapseCategories: false,
      },
    },
    metadata: [],
    tableOfContents: {
      minHeadingLevel: 2,
      maxHeadingLevel: 3,
    },
  },
  baseUrlIssueBanner: true,
  onDuplicateRoutes: "warn",
  staticDirectories: ["static"],
  customFields: {},
  themes: [],
  scripts: [],
  headTags: [],
  stylesheets: [],
  clientModules: [],
  titleDelimiter: "|",
  noIndex: false,
  markdown: {
    mermaid: false,
  },
};
