name: "Create Vulnerability Issue"
description: "Creates a GitHub issue if CRITICAL/HIGH vulnerabilities are found in the scan report"

inputs:
  report_path:
    description: "Path to the vulnerability report file"
    required: true
  package_name:
    description: "Name of the package being released"
    required: true
  package_version:
    description: "Version of the package being released"
    required: true
  release_branch:
    description: "Release branch name"
    required: true
  labels:
    description: "Labels to apply to the created issue"
    required: false
    default: "security"

runs:
  using: "composite"
  steps:
    - name: Check vulnerabilities in report
      id: check_vulns
      shell: bash
      run: |
        set -euo pipefail
        REPORT="${{ inputs.report_path }}"

        if grep -qE "CRITICAL|HIGH" "$REPORT"; then
          echo "found=true" >> "$GITHUB_OUTPUT"
        else
          echo "found=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Create GitHub Issue
      if: steps.check_vulns.outputs.found == 'true'
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        TITLE="🔒 Security vulnerabilities in ${{ inputs.package_name }}@${{ inputs.package_version }}"
        BODY=$(cat <<EOF
        The vulnerability scan for \`${{ inputs.package_name }}@${{ inputs.package_version }}\` on branch \`${{ inputs.release_branch }}\` has detected **CRITICAL/HIGH** vulnerabilities.

        **Release Branch:** \`${{ inputs.release_branch }}\`
        **Package Version:** \`${{ inputs.package_version }}\`

        Please review the attached vulnerability report and take necessary action.

        ---
        _This issue was automatically generated by the Release Pipeline._
        EOF
        )

        gh issue create \
          --title "$TITLE" \
          --body "$BODY" \
          --label "${{ inputs.labels }}"

    - name: Upload report as artifact to issue (comment with attachment)
      if: steps.check_vulns.outputs.found == 'true'
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        ISSUE_NUMBER=$(gh issue list --state open --search "🔒 Security vulnerabilities in ${{ inputs.package_name }}@${{ inputs.package_version }}" --json number --jq '.[0].number')
        if [ -n "$ISSUE_NUMBER" ]; then
          gh issue comment "$ISSUE_NUMBER" --body "📎 Attaching vulnerability report as artifact."
          gh upload-artifact --name vulnerability-report "${{ inputs.report_path }}"
        fi
