name: Run pre-commit hooks

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-hooks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 24.x
        uses: actions/setup-node@v4
        with:
          node-version: 24.x

      - name: Setup npm version 10
        run: npm i -g npm@10 --registry=https://registry.npmjs.org

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-deps-24.x-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-deps-24.x-

      - name: Install Dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build
        run: npm run build

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Cache pre-commit environments
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit-

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit
        env:
          MESSAGE: |
            One or more files did not pass lint/formatting checks.

            To run the checks (and autofix what can be autofixed) locally, run:
              pre-commit run --all-files

            Then commit and push the changes.
        run: |
          set +e
          pre-commit run --all-files --show-diff-on-failure --color always --verbose
          rc=$?
          set -e

          if [ $rc -ne 0 ]; then
              git status
              echo "${MESSAGE}"
              exit 1
          fi
